name: db_gen
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  dart_eval: ^0.7.9
  http: ^1.2.0
  postgres: ^3.2.1
  # path: ^1.8.0


