./gen dag2.act tst.def
./gen dag.act tst.def
./gen json2.act tst.def
./gen json.act tst.def
./gen node.act tst.def
./gen tbl.act tst.def tb2
./gen tst2.act tst.def
./gen group.act tst.def
./gen hash2.act tst.def
./gen hash.act tst.def
./gen s_check.act app.unit
./gen tst3.act tst.def
./gen tst4.act tst.def
./gen tst5.act tst.def
./gen tst6.act tst.def
./gen json3.act tst.def
./gen json4.act tst.def
./gen json5.act tst.def
./gen yaml.act tst.def
